package com.duongan.QuanLyKTX.mapper;

import com.duongan.QuanLyKTX.model.Phong;
import com.duongan.QuanLyKTX.model.PhongExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface PhongMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phong
     *
     * @mbg.generated Tue Mar 22 08:56:15 ICT 2022
     */
    long countByExample(PhongExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phong
     *
     * @mbg.generated Tue Mar 22 08:56:15 ICT 2022
     */
    int deleteByExample(PhongExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phong
     *
     * @mbg.generated Tue Mar 22 08:56:15 ICT 2022
     */
    int deleteByPrimaryKey(String idPhong);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phong
     *
     * @mbg.generated Tue Mar 22 08:56:15 ICT 2022
     */
    int insert(Phong row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phong
     *
     * @mbg.generated Tue Mar 22 08:56:15 ICT 2022
     */
    int insertSelective(Phong row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phong
     *
     * @mbg.generated Tue Mar 22 08:56:15 ICT 2022
     */
    List<Phong> selectByExample(PhongExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phong
     *
     * @mbg.generated Tue Mar 22 08:56:15 ICT 2022
     */
    Phong selectByPrimaryKey(String idPhong);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phong
     *
     * @mbg.generated Tue Mar 22 08:56:15 ICT 2022
     */
    int updateByExampleSelective(@Param("row") Phong row, @Param("example") PhongExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phong
     *
     * @mbg.generated Tue Mar 22 08:56:15 ICT 2022
     */
    int updateByExample(@Param("row") Phong row, @Param("example") PhongExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phong
     *
     * @mbg.generated Tue Mar 22 08:56:15 ICT 2022
     */
    int updateByPrimaryKeySelective(Phong row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phong
     *
     * @mbg.generated Tue Mar 22 08:56:15 ICT 2022
     */
    int updateByPrimaryKey(Phong row);
}