package com.duongan.QuanLyKTX.model;

import java.util.ArrayList;
import java.util.List;

public class PhongExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table phong
     *
     * @mbg.generated Tue Mar 22 08:56:15 ICT 2022
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table phong
     *
     * @mbg.generated Tue Mar 22 08:56:15 ICT 2022
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table phong
     *
     * @mbg.generated Tue Mar 22 08:56:15 ICT 2022
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phong
     *
     * @mbg.generated Tue Mar 22 08:56:15 ICT 2022
     */
    public PhongExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phong
     *
     * @mbg.generated Tue Mar 22 08:56:15 ICT 2022
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phong
     *
     * @mbg.generated Tue Mar 22 08:56:15 ICT 2022
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phong
     *
     * @mbg.generated Tue Mar 22 08:56:15 ICT 2022
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phong
     *
     * @mbg.generated Tue Mar 22 08:56:15 ICT 2022
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phong
     *
     * @mbg.generated Tue Mar 22 08:56:15 ICT 2022
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phong
     *
     * @mbg.generated Tue Mar 22 08:56:15 ICT 2022
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phong
     *
     * @mbg.generated Tue Mar 22 08:56:15 ICT 2022
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phong
     *
     * @mbg.generated Tue Mar 22 08:56:15 ICT 2022
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phong
     *
     * @mbg.generated Tue Mar 22 08:56:15 ICT 2022
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phong
     *
     * @mbg.generated Tue Mar 22 08:56:15 ICT 2022
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table phong
     *
     * @mbg.generated Tue Mar 22 08:56:15 ICT 2022
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdPhongIsNull() {
            addCriterion("id_phong is null");
            return (Criteria) this;
        }

        public Criteria andIdPhongIsNotNull() {
            addCriterion("id_phong is not null");
            return (Criteria) this;
        }

        public Criteria andIdPhongEqualTo(String value) {
            addCriterion("id_phong =", value, "idPhong");
            return (Criteria) this;
        }

        public Criteria andIdPhongNotEqualTo(String value) {
            addCriterion("id_phong <>", value, "idPhong");
            return (Criteria) this;
        }

        public Criteria andIdPhongGreaterThan(String value) {
            addCriterion("id_phong >", value, "idPhong");
            return (Criteria) this;
        }

        public Criteria andIdPhongGreaterThanOrEqualTo(String value) {
            addCriterion("id_phong >=", value, "idPhong");
            return (Criteria) this;
        }

        public Criteria andIdPhongLessThan(String value) {
            addCriterion("id_phong <", value, "idPhong");
            return (Criteria) this;
        }

        public Criteria andIdPhongLessThanOrEqualTo(String value) {
            addCriterion("id_phong <=", value, "idPhong");
            return (Criteria) this;
        }

        public Criteria andIdPhongLike(String value) {
            addCriterion("id_phong like", value, "idPhong");
            return (Criteria) this;
        }

        public Criteria andIdPhongNotLike(String value) {
            addCriterion("id_phong not like", value, "idPhong");
            return (Criteria) this;
        }

        public Criteria andIdPhongIn(List<String> values) {
            addCriterion("id_phong in", values, "idPhong");
            return (Criteria) this;
        }

        public Criteria andIdPhongNotIn(List<String> values) {
            addCriterion("id_phong not in", values, "idPhong");
            return (Criteria) this;
        }

        public Criteria andIdPhongBetween(String value1, String value2) {
            addCriterion("id_phong between", value1, value2, "idPhong");
            return (Criteria) this;
        }

        public Criteria andIdPhongNotBetween(String value1, String value2) {
            addCriterion("id_phong not between", value1, value2, "idPhong");
            return (Criteria) this;
        }

        public Criteria andLoaiphongIsNull() {
            addCriterion("loaiphong is null");
            return (Criteria) this;
        }

        public Criteria andLoaiphongIsNotNull() {
            addCriterion("loaiphong is not null");
            return (Criteria) this;
        }

        public Criteria andLoaiphongEqualTo(String value) {
            addCriterion("loaiphong =", value, "loaiphong");
            return (Criteria) this;
        }

        public Criteria andLoaiphongNotEqualTo(String value) {
            addCriterion("loaiphong <>", value, "loaiphong");
            return (Criteria) this;
        }

        public Criteria andLoaiphongGreaterThan(String value) {
            addCriterion("loaiphong >", value, "loaiphong");
            return (Criteria) this;
        }

        public Criteria andLoaiphongGreaterThanOrEqualTo(String value) {
            addCriterion("loaiphong >=", value, "loaiphong");
            return (Criteria) this;
        }

        public Criteria andLoaiphongLessThan(String value) {
            addCriterion("loaiphong <", value, "loaiphong");
            return (Criteria) this;
        }

        public Criteria andLoaiphongLessThanOrEqualTo(String value) {
            addCriterion("loaiphong <=", value, "loaiphong");
            return (Criteria) this;
        }

        public Criteria andLoaiphongLike(String value) {
            addCriterion("loaiphong like", value, "loaiphong");
            return (Criteria) this;
        }

        public Criteria andLoaiphongNotLike(String value) {
            addCriterion("loaiphong not like", value, "loaiphong");
            return (Criteria) this;
        }

        public Criteria andLoaiphongIn(List<String> values) {
            addCriterion("loaiphong in", values, "loaiphong");
            return (Criteria) this;
        }

        public Criteria andLoaiphongNotIn(List<String> values) {
            addCriterion("loaiphong not in", values, "loaiphong");
            return (Criteria) this;
        }

        public Criteria andLoaiphongBetween(String value1, String value2) {
            addCriterion("loaiphong between", value1, value2, "loaiphong");
            return (Criteria) this;
        }

        public Criteria andLoaiphongNotBetween(String value1, String value2) {
            addCriterion("loaiphong not between", value1, value2, "loaiphong");
            return (Criteria) this;
        }

        public Criteria andSoluongsvIsNull() {
            addCriterion("soluongSV is null");
            return (Criteria) this;
        }

        public Criteria andSoluongsvIsNotNull() {
            addCriterion("soluongSV is not null");
            return (Criteria) this;
        }

        public Criteria andSoluongsvEqualTo(Byte value) {
            addCriterion("soluongSV =", value, "soluongsv");
            return (Criteria) this;
        }

        public Criteria andSoluongsvNotEqualTo(Byte value) {
            addCriterion("soluongSV <>", value, "soluongsv");
            return (Criteria) this;
        }

        public Criteria andSoluongsvGreaterThan(Byte value) {
            addCriterion("soluongSV >", value, "soluongsv");
            return (Criteria) this;
        }

        public Criteria andSoluongsvGreaterThanOrEqualTo(Byte value) {
            addCriterion("soluongSV >=", value, "soluongsv");
            return (Criteria) this;
        }

        public Criteria andSoluongsvLessThan(Byte value) {
            addCriterion("soluongSV <", value, "soluongsv");
            return (Criteria) this;
        }

        public Criteria andSoluongsvLessThanOrEqualTo(Byte value) {
            addCriterion("soluongSV <=", value, "soluongsv");
            return (Criteria) this;
        }

        public Criteria andSoluongsvIn(List<Byte> values) {
            addCriterion("soluongSV in", values, "soluongsv");
            return (Criteria) this;
        }

        public Criteria andSoluongsvNotIn(List<Byte> values) {
            addCriterion("soluongSV not in", values, "soluongsv");
            return (Criteria) this;
        }

        public Criteria andSoluongsvBetween(Byte value1, Byte value2) {
            addCriterion("soluongSV between", value1, value2, "soluongsv");
            return (Criteria) this;
        }

        public Criteria andSoluongsvNotBetween(Byte value1, Byte value2) {
            addCriterion("soluongSV not between", value1, value2, "soluongsv");
            return (Criteria) this;
        }

        public Criteria andIdToanhaIsNull() {
            addCriterion("id_toanha is null");
            return (Criteria) this;
        }

        public Criteria andIdToanhaIsNotNull() {
            addCriterion("id_toanha is not null");
            return (Criteria) this;
        }

        public Criteria andIdToanhaEqualTo(String value) {
            addCriterion("id_toanha =", value, "idToanha");
            return (Criteria) this;
        }

        public Criteria andIdToanhaNotEqualTo(String value) {
            addCriterion("id_toanha <>", value, "idToanha");
            return (Criteria) this;
        }

        public Criteria andIdToanhaGreaterThan(String value) {
            addCriterion("id_toanha >", value, "idToanha");
            return (Criteria) this;
        }

        public Criteria andIdToanhaGreaterThanOrEqualTo(String value) {
            addCriterion("id_toanha >=", value, "idToanha");
            return (Criteria) this;
        }

        public Criteria andIdToanhaLessThan(String value) {
            addCriterion("id_toanha <", value, "idToanha");
            return (Criteria) this;
        }

        public Criteria andIdToanhaLessThanOrEqualTo(String value) {
            addCriterion("id_toanha <=", value, "idToanha");
            return (Criteria) this;
        }

        public Criteria andIdToanhaLike(String value) {
            addCriterion("id_toanha like", value, "idToanha");
            return (Criteria) this;
        }

        public Criteria andIdToanhaNotLike(String value) {
            addCriterion("id_toanha not like", value, "idToanha");
            return (Criteria) this;
        }

        public Criteria andIdToanhaIn(List<String> values) {
            addCriterion("id_toanha in", values, "idToanha");
            return (Criteria) this;
        }

        public Criteria andIdToanhaNotIn(List<String> values) {
            addCriterion("id_toanha not in", values, "idToanha");
            return (Criteria) this;
        }

        public Criteria andIdToanhaBetween(String value1, String value2) {
            addCriterion("id_toanha between", value1, value2, "idToanha");
            return (Criteria) this;
        }

        public Criteria andIdToanhaNotBetween(String value1, String value2) {
            addCriterion("id_toanha not between", value1, value2, "idToanha");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table phong
     *
     * @mbg.generated do_not_delete_during_merge Tue Mar 22 08:56:15 ICT 2022
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table phong
     *
     * @mbg.generated Tue Mar 22 08:56:15 ICT 2022
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}