package com.duongan.QuanLyKTX.model;

public class Phong {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phong.id_phong
     *
     * @mbg.generated Tue Mar 22 08:56:15 ICT 2022
     */
    private String idPhong;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phong.loaiphong
     *
     * @mbg.generated Tue Mar 22 08:56:15 ICT 2022
     */
    private String loaiphong;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phong.soluongSV
     *
     * @mbg.generated Tue Mar 22 08:56:15 ICT 2022
     */
    private Byte soluongsv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phong.id_toanha
     *
     * @mbg.generated Tue Mar 22 08:56:15 ICT 2022
     */
    private String idToanha;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phong.id_phong
     *
     * @return the value of phong.id_phong
     *
     * @mbg.generated Tue Mar 22 08:56:15 ICT 2022
     */
    public String getIdPhong() {
        return idPhong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phong.id_phong
     *
     * @param idPhong the value for phong.id_phong
     *
     * @mbg.generated Tue Mar 22 08:56:15 ICT 2022
     */
    public void setIdPhong(String idPhong) {
        this.idPhong = idPhong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phong.loaiphong
     *
     * @return the value of phong.loaiphong
     *
     * @mbg.generated Tue Mar 22 08:56:15 ICT 2022
     */
    public String getLoaiphong() {
        return loaiphong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phong.loaiphong
     *
     * @param loaiphong the value for phong.loaiphong
     *
     * @mbg.generated Tue Mar 22 08:56:15 ICT 2022
     */
    public void setLoaiphong(String loaiphong) {
        this.loaiphong = loaiphong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phong.soluongSV
     *
     * @return the value of phong.soluongSV
     *
     * @mbg.generated Tue Mar 22 08:56:15 ICT 2022
     */
    public Byte getSoluongsv() {
        return soluongsv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phong.soluongSV
     *
     * @param soluongsv the value for phong.soluongSV
     *
     * @mbg.generated Tue Mar 22 08:56:15 ICT 2022
     */
    public void setSoluongsv(Byte soluongsv) {
        this.soluongsv = soluongsv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phong.id_toanha
     *
     * @return the value of phong.id_toanha
     *
     * @mbg.generated Tue Mar 22 08:56:15 ICT 2022
     */
    public String getIdToanha() {
        return idToanha;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phong.id_toanha
     *
     * @param idToanha the value for phong.id_toanha
     *
     * @mbg.generated Tue Mar 22 08:56:15 ICT 2022
     */
    public void setIdToanha(String idToanha) {
        this.idToanha = idToanha;
    }
}