package com.duongan.QuanLyKTX.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Iterator;

public class UserExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table user
	 * @mbg.generated  Tue Mar 22 08:56:15 ICT 2022
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table user
	 * @mbg.generated  Tue Mar 22 08:56:15 ICT 2022
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table user
	 * @mbg.generated  Tue Mar 22 08:56:15 ICT 2022
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Tue Mar 22 08:56:15 ICT 2022
	 */
	public UserExample() {
		oredCriteria = new ArrayList<>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Tue Mar 22 08:56:15 ICT 2022
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Tue Mar 22 08:56:15 ICT 2022
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Tue Mar 22 08:56:15 ICT 2022
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Tue Mar 22 08:56:15 ICT 2022
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Tue Mar 22 08:56:15 ICT 2022
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Tue Mar 22 08:56:15 ICT 2022
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Tue Mar 22 08:56:15 ICT 2022
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Tue Mar 22 08:56:15 ICT 2022
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Tue Mar 22 08:56:15 ICT 2022
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Tue Mar 22 08:56:15 ICT 2022
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table user
	 * @mbg.generated  Tue Mar 22 08:56:15 ICT 2022
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		protected void addCriterionForJDBCDate(String condition, Date value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value.getTime()), property);
		}

		protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property + " cannot be null or empty");
			}
			List<java.sql.Date> dateList = new ArrayList<>();
			Iterator<Date> iter = values.iterator();
			while (iter.hasNext()) {
				dateList.add(new java.sql.Date(iter.next().getTime()));
			}
			addCriterion(condition, dateList, property);
		}

		protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
		}

		public Criteria andUsernameIsNull() {
			addCriterion("username is null");
			return (Criteria) this;
		}

		public Criteria andUsernameIsNotNull() {
			addCriterion("username is not null");
			return (Criteria) this;
		}

		public Criteria andUsernameEqualTo(String value) {
			addCriterion("username =", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameNotEqualTo(String value) {
			addCriterion("username <>", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameGreaterThan(String value) {
			addCriterion("username >", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameGreaterThanOrEqualTo(String value) {
			addCriterion("username >=", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameLessThan(String value) {
			addCriterion("username <", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameLessThanOrEqualTo(String value) {
			addCriterion("username <=", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameLike(String value) {
			addCriterion("username like", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameNotLike(String value) {
			addCriterion("username not like", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameIn(List<String> values) {
			addCriterion("username in", values, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameNotIn(List<String> values) {
			addCriterion("username not in", values, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameBetween(String value1, String value2) {
			addCriterion("username between", value1, value2, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameNotBetween(String value1, String value2) {
			addCriterion("username not between", value1, value2, "username");
			return (Criteria) this;
		}

		public Criteria andPasswordIsNull() {
			addCriterion("password is null");
			return (Criteria) this;
		}

		public Criteria andPasswordIsNotNull() {
			addCriterion("password is not null");
			return (Criteria) this;
		}

		public Criteria andPasswordEqualTo(String value) {
			addCriterion("password =", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotEqualTo(String value) {
			addCriterion("password <>", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordGreaterThan(String value) {
			addCriterion("password >", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordGreaterThanOrEqualTo(String value) {
			addCriterion("password >=", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordLessThan(String value) {
			addCriterion("password <", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordLessThanOrEqualTo(String value) {
			addCriterion("password <=", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordLike(String value) {
			addCriterion("password like", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotLike(String value) {
			addCriterion("password not like", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordIn(List<String> values) {
			addCriterion("password in", values, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotIn(List<String> values) {
			addCriterion("password not in", values, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordBetween(String value1, String value2) {
			addCriterion("password between", value1, value2, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotBetween(String value1, String value2) {
			addCriterion("password not between", value1, value2, "password");
			return (Criteria) this;
		}

		public Criteria andEmailIsNull() {
			addCriterion("email is null");
			return (Criteria) this;
		}

		public Criteria andEmailIsNotNull() {
			addCriterion("email is not null");
			return (Criteria) this;
		}

		public Criteria andEmailEqualTo(String value) {
			addCriterion("email =", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotEqualTo(String value) {
			addCriterion("email <>", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailGreaterThan(String value) {
			addCriterion("email >", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailGreaterThanOrEqualTo(String value) {
			addCriterion("email >=", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLessThan(String value) {
			addCriterion("email <", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLessThanOrEqualTo(String value) {
			addCriterion("email <=", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLike(String value) {
			addCriterion("email like", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotLike(String value) {
			addCriterion("email not like", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailIn(List<String> values) {
			addCriterion("email in", values, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotIn(List<String> values) {
			addCriterion("email not in", values, "email");
			return (Criteria) this;
		}

		public Criteria andEmailBetween(String value1, String value2) {
			addCriterion("email between", value1, value2, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotBetween(String value1, String value2) {
			addCriterion("email not between", value1, value2, "email");
			return (Criteria) this;
		}

		public Criteria andPhoneIsNull() {
			addCriterion("phone is null");
			return (Criteria) this;
		}

		public Criteria andPhoneIsNotNull() {
			addCriterion("phone is not null");
			return (Criteria) this;
		}

		public Criteria andPhoneEqualTo(String value) {
			addCriterion("phone =", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneNotEqualTo(String value) {
			addCriterion("phone <>", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneGreaterThan(String value) {
			addCriterion("phone >", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneGreaterThanOrEqualTo(String value) {
			addCriterion("phone >=", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneLessThan(String value) {
			addCriterion("phone <", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneLessThanOrEqualTo(String value) {
			addCriterion("phone <=", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneLike(String value) {
			addCriterion("phone like", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneNotLike(String value) {
			addCriterion("phone not like", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneIn(List<String> values) {
			addCriterion("phone in", values, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneNotIn(List<String> values) {
			addCriterion("phone not in", values, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneBetween(String value1, String value2) {
			addCriterion("phone between", value1, value2, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneNotBetween(String value1, String value2) {
			addCriterion("phone not between", value1, value2, "phone");
			return (Criteria) this;
		}

		public Criteria andNgaysinhIsNull() {
			addCriterion("ngaysinh is null");
			return (Criteria) this;
		}

		public Criteria andNgaysinhIsNotNull() {
			addCriterion("ngaysinh is not null");
			return (Criteria) this;
		}

		public Criteria andNgaysinhEqualTo(Date value) {
			addCriterionForJDBCDate("ngaysinh =", value, "ngaysinh");
			return (Criteria) this;
		}

		public Criteria andNgaysinhNotEqualTo(Date value) {
			addCriterionForJDBCDate("ngaysinh <>", value, "ngaysinh");
			return (Criteria) this;
		}

		public Criteria andNgaysinhGreaterThan(Date value) {
			addCriterionForJDBCDate("ngaysinh >", value, "ngaysinh");
			return (Criteria) this;
		}

		public Criteria andNgaysinhGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("ngaysinh >=", value, "ngaysinh");
			return (Criteria) this;
		}

		public Criteria andNgaysinhLessThan(Date value) {
			addCriterionForJDBCDate("ngaysinh <", value, "ngaysinh");
			return (Criteria) this;
		}

		public Criteria andNgaysinhLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("ngaysinh <=", value, "ngaysinh");
			return (Criteria) this;
		}

		public Criteria andNgaysinhIn(List<Date> values) {
			addCriterionForJDBCDate("ngaysinh in", values, "ngaysinh");
			return (Criteria) this;
		}

		public Criteria andNgaysinhNotIn(List<Date> values) {
			addCriterionForJDBCDate("ngaysinh not in", values, "ngaysinh");
			return (Criteria) this;
		}

		public Criteria andNgaysinhBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("ngaysinh between", value1, value2, "ngaysinh");
			return (Criteria) this;
		}

		public Criteria andNgaysinhNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("ngaysinh not between", value1, value2, "ngaysinh");
			return (Criteria) this;
		}

		public Criteria andDiachiIsNull() {
			addCriterion("diachi is null");
			return (Criteria) this;
		}

		public Criteria andDiachiIsNotNull() {
			addCriterion("diachi is not null");
			return (Criteria) this;
		}

		public Criteria andDiachiEqualTo(String value) {
			addCriterion("diachi =", value, "diachi");
			return (Criteria) this;
		}

		public Criteria andDiachiNotEqualTo(String value) {
			addCriterion("diachi <>", value, "diachi");
			return (Criteria) this;
		}

		public Criteria andDiachiGreaterThan(String value) {
			addCriterion("diachi >", value, "diachi");
			return (Criteria) this;
		}

		public Criteria andDiachiGreaterThanOrEqualTo(String value) {
			addCriterion("diachi >=", value, "diachi");
			return (Criteria) this;
		}

		public Criteria andDiachiLessThan(String value) {
			addCriterion("diachi <", value, "diachi");
			return (Criteria) this;
		}

		public Criteria andDiachiLessThanOrEqualTo(String value) {
			addCriterion("diachi <=", value, "diachi");
			return (Criteria) this;
		}

		public Criteria andDiachiLike(String value) {
			addCriterion("diachi like", value, "diachi");
			return (Criteria) this;
		}

		public Criteria andDiachiNotLike(String value) {
			addCriterion("diachi not like", value, "diachi");
			return (Criteria) this;
		}

		public Criteria andDiachiIn(List<String> values) {
			addCriterion("diachi in", values, "diachi");
			return (Criteria) this;
		}

		public Criteria andDiachiNotIn(List<String> values) {
			addCriterion("diachi not in", values, "diachi");
			return (Criteria) this;
		}

		public Criteria andDiachiBetween(String value1, String value2) {
			addCriterion("diachi between", value1, value2, "diachi");
			return (Criteria) this;
		}

		public Criteria andDiachiNotBetween(String value1, String value2) {
			addCriterion("diachi not between", value1, value2, "diachi");
			return (Criteria) this;
		}

		public Criteria andTruonghocIsNull() {
			addCriterion("truonghoc is null");
			return (Criteria) this;
		}

		public Criteria andTruonghocIsNotNull() {
			addCriterion("truonghoc is not null");
			return (Criteria) this;
		}

		public Criteria andTruonghocEqualTo(String value) {
			addCriterion("truonghoc =", value, "truonghoc");
			return (Criteria) this;
		}

		public Criteria andTruonghocNotEqualTo(String value) {
			addCriterion("truonghoc <>", value, "truonghoc");
			return (Criteria) this;
		}

		public Criteria andTruonghocGreaterThan(String value) {
			addCriterion("truonghoc >", value, "truonghoc");
			return (Criteria) this;
		}

		public Criteria andTruonghocGreaterThanOrEqualTo(String value) {
			addCriterion("truonghoc >=", value, "truonghoc");
			return (Criteria) this;
		}

		public Criteria andTruonghocLessThan(String value) {
			addCriterion("truonghoc <", value, "truonghoc");
			return (Criteria) this;
		}

		public Criteria andTruonghocLessThanOrEqualTo(String value) {
			addCriterion("truonghoc <=", value, "truonghoc");
			return (Criteria) this;
		}

		public Criteria andTruonghocLike(String value) {
			addCriterion("truonghoc like", value, "truonghoc");
			return (Criteria) this;
		}

		public Criteria andTruonghocNotLike(String value) {
			addCriterion("truonghoc not like", value, "truonghoc");
			return (Criteria) this;
		}

		public Criteria andTruonghocIn(List<String> values) {
			addCriterion("truonghoc in", values, "truonghoc");
			return (Criteria) this;
		}

		public Criteria andTruonghocNotIn(List<String> values) {
			addCriterion("truonghoc not in", values, "truonghoc");
			return (Criteria) this;
		}

		public Criteria andTruonghocBetween(String value1, String value2) {
			addCriterion("truonghoc between", value1, value2, "truonghoc");
			return (Criteria) this;
		}

		public Criteria andTruonghocNotBetween(String value1, String value2) {
			addCriterion("truonghoc not between", value1, value2, "truonghoc");
			return (Criteria) this;
		}

		public Criteria andQuyensudungIsNull() {
			addCriterion("quyensudung is null");
			return (Criteria) this;
		}

		public Criteria andQuyensudungIsNotNull() {
			addCriterion("quyensudung is not null");
			return (Criteria) this;
		}

		public Criteria andQuyensudungEqualTo(String value) {
			addCriterion("quyensudung =", value, "quyensudung");
			return (Criteria) this;
		}

		public Criteria andQuyensudungNotEqualTo(String value) {
			addCriterion("quyensudung <>", value, "quyensudung");
			return (Criteria) this;
		}

		public Criteria andQuyensudungGreaterThan(String value) {
			addCriterion("quyensudung >", value, "quyensudung");
			return (Criteria) this;
		}

		public Criteria andQuyensudungGreaterThanOrEqualTo(String value) {
			addCriterion("quyensudung >=", value, "quyensudung");
			return (Criteria) this;
		}

		public Criteria andQuyensudungLessThan(String value) {
			addCriterion("quyensudung <", value, "quyensudung");
			return (Criteria) this;
		}

		public Criteria andQuyensudungLessThanOrEqualTo(String value) {
			addCriterion("quyensudung <=", value, "quyensudung");
			return (Criteria) this;
		}

		public Criteria andQuyensudungLike(String value) {
			addCriterion("quyensudung like", value, "quyensudung");
			return (Criteria) this;
		}

		public Criteria andQuyensudungNotLike(String value) {
			addCriterion("quyensudung not like", value, "quyensudung");
			return (Criteria) this;
		}

		public Criteria andQuyensudungIn(List<String> values) {
			addCriterion("quyensudung in", values, "quyensudung");
			return (Criteria) this;
		}

		public Criteria andQuyensudungNotIn(List<String> values) {
			addCriterion("quyensudung not in", values, "quyensudung");
			return (Criteria) this;
		}

		public Criteria andQuyensudungBetween(String value1, String value2) {
			addCriterion("quyensudung between", value1, value2, "quyensudung");
			return (Criteria) this;
		}

		public Criteria andQuyensudungNotBetween(String value1, String value2) {
			addCriterion("quyensudung not between", value1, value2, "quyensudung");
			return (Criteria) this;
		}

		public Criteria andNgaytaoIsNull() {
			addCriterion("ngaytao is null");
			return (Criteria) this;
		}

		public Criteria andNgaytaoIsNotNull() {
			addCriterion("ngaytao is not null");
			return (Criteria) this;
		}

		public Criteria andNgaytaoEqualTo(Date value) {
			addCriterion("ngaytao =", value, "ngaytao");
			return (Criteria) this;
		}

		public Criteria andNgaytaoNotEqualTo(Date value) {
			addCriterion("ngaytao <>", value, "ngaytao");
			return (Criteria) this;
		}

		public Criteria andNgaytaoGreaterThan(Date value) {
			addCriterion("ngaytao >", value, "ngaytao");
			return (Criteria) this;
		}

		public Criteria andNgaytaoGreaterThanOrEqualTo(Date value) {
			addCriterion("ngaytao >=", value, "ngaytao");
			return (Criteria) this;
		}

		public Criteria andNgaytaoLessThan(Date value) {
			addCriterion("ngaytao <", value, "ngaytao");
			return (Criteria) this;
		}

		public Criteria andNgaytaoLessThanOrEqualTo(Date value) {
			addCriterion("ngaytao <=", value, "ngaytao");
			return (Criteria) this;
		}

		public Criteria andNgaytaoIn(List<Date> values) {
			addCriterion("ngaytao in", values, "ngaytao");
			return (Criteria) this;
		}

		public Criteria andNgaytaoNotIn(List<Date> values) {
			addCriterion("ngaytao not in", values, "ngaytao");
			return (Criteria) this;
		}

		public Criteria andNgaytaoBetween(Date value1, Date value2) {
			addCriterion("ngaytao between", value1, value2, "ngaytao");
			return (Criteria) this;
		}

		public Criteria andNgaytaoNotBetween(Date value1, Date value2) {
			addCriterion("ngaytao not between", value1, value2, "ngaytao");
			return (Criteria) this;
		}

		public Criteria andAvatarIsNull() {
			addCriterion("avatar is null");
			return (Criteria) this;
		}

		public Criteria andAvatarIsNotNull() {
			addCriterion("avatar is not null");
			return (Criteria) this;
		}

		public Criteria andAvatarEqualTo(String value) {
			addCriterion("avatar =", value, "avatar");
			return (Criteria) this;
		}

		public Criteria andAvatarNotEqualTo(String value) {
			addCriterion("avatar <>", value, "avatar");
			return (Criteria) this;
		}

		public Criteria andAvatarGreaterThan(String value) {
			addCriterion("avatar >", value, "avatar");
			return (Criteria) this;
		}

		public Criteria andAvatarGreaterThanOrEqualTo(String value) {
			addCriterion("avatar >=", value, "avatar");
			return (Criteria) this;
		}

		public Criteria andAvatarLessThan(String value) {
			addCriterion("avatar <", value, "avatar");
			return (Criteria) this;
		}

		public Criteria andAvatarLessThanOrEqualTo(String value) {
			addCriterion("avatar <=", value, "avatar");
			return (Criteria) this;
		}

		public Criteria andAvatarLike(String value) {
			addCriterion("avatar like", value, "avatar");
			return (Criteria) this;
		}

		public Criteria andAvatarNotLike(String value) {
			addCriterion("avatar not like", value, "avatar");
			return (Criteria) this;
		}

		public Criteria andAvatarIn(List<String> values) {
			addCriterion("avatar in", values, "avatar");
			return (Criteria) this;
		}

		public Criteria andAvatarNotIn(List<String> values) {
			addCriterion("avatar not in", values, "avatar");
			return (Criteria) this;
		}

		public Criteria andAvatarBetween(String value1, String value2) {
			addCriterion("avatar between", value1, value2, "avatar");
			return (Criteria) this;
		}

		public Criteria andAvatarNotBetween(String value1, String value2) {
			addCriterion("avatar not between", value1, value2, "avatar");
			return (Criteria) this;
		}

		public Criteria andIdPhongIsNull() {
			addCriterion("id_phong is null");
			return (Criteria) this;
		}

		public Criteria andIdPhongIsNotNull() {
			addCriterion("id_phong is not null");
			return (Criteria) this;
		}

		public Criteria andIdPhongEqualTo(String value) {
			addCriterion("id_phong =", value, "idPhong");
			return (Criteria) this;
		}

		public Criteria andIdPhongNotEqualTo(String value) {
			addCriterion("id_phong <>", value, "idPhong");
			return (Criteria) this;
		}

		public Criteria andIdPhongGreaterThan(String value) {
			addCriterion("id_phong >", value, "idPhong");
			return (Criteria) this;
		}

		public Criteria andIdPhongGreaterThanOrEqualTo(String value) {
			addCriterion("id_phong >=", value, "idPhong");
			return (Criteria) this;
		}

		public Criteria andIdPhongLessThan(String value) {
			addCriterion("id_phong <", value, "idPhong");
			return (Criteria) this;
		}

		public Criteria andIdPhongLessThanOrEqualTo(String value) {
			addCriterion("id_phong <=", value, "idPhong");
			return (Criteria) this;
		}

		public Criteria andIdPhongLike(String value) {
			addCriterion("id_phong like", value, "idPhong");
			return (Criteria) this;
		}

		public Criteria andIdPhongNotLike(String value) {
			addCriterion("id_phong not like", value, "idPhong");
			return (Criteria) this;
		}

		public Criteria andIdPhongIn(List<String> values) {
			addCriterion("id_phong in", values, "idPhong");
			return (Criteria) this;
		}

		public Criteria andIdPhongNotIn(List<String> values) {
			addCriterion("id_phong not in", values, "idPhong");
			return (Criteria) this;
		}

		public Criteria andIdPhongBetween(String value1, String value2) {
			addCriterion("id_phong between", value1, value2, "idPhong");
			return (Criteria) this;
		}

		public Criteria andIdPhongNotBetween(String value1, String value2) {
			addCriterion("id_phong not between", value1, value2, "idPhong");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table user
	 * @mbg.generated  Tue Mar 22 08:56:15 ICT 2022
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user
     *
     * @mbg.generated do_not_delete_during_merge Tue Mar 22 08:56:15 ICT 2022
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }
}